# Generated by Django 3.0.7 on 2020-06-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cringe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(default='Question', max_length=10),
        ),
    ]
