# Generated by Django 3.0.7 on 2020-06-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cringe_app', '0004_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
